---
- hosts: localhost
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t devops-image:latest .
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag devops-image devopscloudage/simple-devops-image

    - name: push image on to dockerhub
      command: docker push devopscloudage/devops-image

    - name: remove docker images from ansible server
      command: docker rmi tomcat devops-image:latest devopscloudage/devops-image
      ignore_errors: yes
